// Generates src/breaks/generated/gecko-break-data.ts from Firefox 156's baked ICU4X segmenter data
// (firefox-156.0/intl/icu_segmenter_data/data, icu4x commit 3579f233, CLDR 48, icuexport release-78.1). Each file is
// checked against rebuild/data/gecko/segmenter-data-sha256.json.
// usage: bun rebuild/tools/gen-gecko-data.ts
//
// A data file is databake output: RuleBreakData { property_table: CodePointTrie::from_parts(header, index:
// ZeroVec<u16>, data: ZeroVec<u8>, error_value: u8), break_state_table: ZeroVec<u8>, ... } (icu_segmenter 2.1.2
// src/provider/mod.rs:151-180). The parser follows the groundwork's runtime-parity/gecko/tools/gen-line-data.ts.
//
// The Gecko port extends this file when it needs more Firefox data (the LSTM models for Thai, Lao, Khmer and Burmese are
// segmenter_lstm_auto_v1.rs.data; DESIGN.md §6 explains why the first port uses the running Firefox's Intl.Segmenter).
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { BROWSER_ENGINES, DATA, REBUILD, readVerified, writeModule } from './gen-shared.ts'

type HashEntry = { file: string; bytes: number; sha256_firefox156: string }
const hashes = JSON.parse(readFileSync(resolve(DATA, 'gecko/segmenter-data-sha256.json'), 'utf8')) as { files: HashEntry[] }
const SOURCE = resolve(BROWSER_ENGINES, 'firefox-156.0/intl/icu_segmenter_data/data')

function parseByteString(literal: string): Uint8Array {
  const bytes: number[] = []
  for (let i = 0; i < literal.length; i++) {
    const c = literal[i]!
    if (c !== '\\') { bytes.push(c.charCodeAt(0)); continue }
    const e = literal[++i]!
    if (e === 'x') { bytes.push(parseInt(literal.slice(i + 1, i + 3), 16)); i += 2 }
    else if (e === '0') bytes.push(0)
    else if (e === 'n') bytes.push(10)
    else if (e === 'r') bytes.push(13)
    else if (e === 't') bytes.push(9)
    else if (e === '\\' || e === '"' || e === "'") bytes.push(e.charCodeAt(0))
    else throw new Error('unknown escape \\' + e)
  }
  return new Uint8Array(bytes)
}

function ruleData(file: string): string {
  let hash: HashEntry | undefined
  for (let i = 0; i < hashes.files.length; i++) if (hashes.files[i]!.file === file) hash = hashes.files[i]!
  if (hash === undefined) throw new Error(`segmenter-data-sha256.json has no ${file}`)
  const text = new TextDecoder().decode(readVerified(resolve(SOURCE, file), hash.sha256_firefox156))
  if (!/trie_type : icu :: collections :: codepointtrie :: TrieType :: Small/.test(text)) throw new Error(`${file}: expected a small trie`)
  if (!/\) \} , 0u8\) \} , break_state_table/.test(text)) throw new Error(`${file}: expected trie error value 0u8`)
  const literals = [...text.matchAll(/b"((?:[^"\\]|\\.)*)"/g)].map(m => parseByteString(m[1]!))
  const [index, data, states] = literals as [Uint8Array, Uint8Array, Uint8Array]
  const num = (name: string): number => {
    const m = text.match(new RegExp(name + ' : (\\d+)u'))
    if (m === null) throw new Error(`${file}: missing ${name}`)
    return Number(m[1])
  }
  const propertyCount = num('property_count')
  if (index.length % 2 !== 0) throw new Error(`${file}: odd index length`)
  if (states.length !== propertyCount * propertyCount) throw new Error(`${file}: state table is not property_count squared`)
  const b64 = (bytes: Uint8Array) => Buffer.from(bytes).toString('base64')
  return `{
  // ${file}: sha256 ${hash.sha256_firefox156}
  highStart: ${num('high_start')},
  propertyCount: ${propertyCount},
  lastCodepointProperty: ${num('last_codepoint_property')},
  sotProperty: ${num('sot_property')},
  eotProperty: ${num('eot_property')},
  complexProperty: ${num('complex_property')},
  trieIndexBase64: '${b64(index)}',
  trieDataBase64: '${b64(data)}',
  breakStatesBase64: '${b64(states)}',
}`
}

writeModule(resolve(REBUILD, 'src/breaks/generated/gecko-break-data.ts'), `// Generated by rebuild/tools/gen-gecko-data.ts from Firefox 156.0's intl/icu_segmenter_data. Do not edit.
// icu4x commit 3579f233, icuexport release-78.1, CLDR 48. Line classes are icu_segmenter 2.1.2 line.rs:20-128.
import type { Icu4xRuleDataSource } from '../icu4x.js'

export const geckoLineBreakData: Icu4xRuleDataSource = ${ruleData('segmenter_break_line_v1.rs.data')}

export const geckoGraphemeData: Icu4xRuleDataSource = ${ruleData('segmenter_break_grapheme_cluster_v1.rs.data')}
`)
