// Generates src/breaks/generated/blink-break-tables.ts from rebuild/data/blink (Chrome 153.0.8010.48 icudtl.dat, ICU
// 78.2): the line tables Blink's LazyLineBreakIterator opens, char.brk for grapheme boundaries, and Blink's generated
// kFastLineBreakTable. Every input is checked against data/blink/manifest.json.
// usage: bun rebuild/tools/gen-blink-data.ts
//
// The Blink port extends this file (and only this generator) when it needs more Blink data, for example Line_Break and
// General_Category values from ICU 78.2 for break-all and keep-all (specs/blink-text.md §2.F.5).
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { DATA, REBUILD, base64, parsePairBitmap, readVerified, writeModule } from './gen-shared.ts'

type ManifestEntry = { name: string; bytes: number; sha256: string }
const manifest = JSON.parse(readFileSync(resolve(DATA, 'blink/manifest.json'), 'utf8')) as { entries: ManifestEntry[] }

function entry(name: string): ManifestEntry {
  for (let i = 0; i < manifest.entries.length; i++) if (manifest.entries[i]!.name === name) return manifest.entries[i]!
  throw new Error(`data/blink/manifest.json has no ${name}`)
}

// Table names as ICU's brkitr resource bundles name them (specs/blink-canvas.md §2.2-2.3). The phrase tables need the
// jaml model and word-break: auto-phrase, which the input model doesn't have (DESIGN.md §1).
const tables = ['line', 'line_normal', 'line_normal_cj', 'line_loose', 'line_loose_cj', 'char'] as const

const lines: string[] = []
for (let i = 0; i < tables.length; i++) {
  const name = tables[i]!
  const e = entry(`${name}.brk`)
  const bytes = readVerified(resolve(DATA, 'blink', e.name), e.sha256)
  lines.push(`  // ${e.name}: ${e.bytes} bytes, sha256 ${e.sha256}`)
  lines.push(`  ${name}: '${base64(bytes)}',`)
}

const header = entry('break_iterator_data_inline_header.h')
const headerText = new TextDecoder().decode(readVerified(resolve(DATA, 'blink', header.name), header.sha256))
const pairs = parsePairBitmap(headerText, 'kFastLineBreakTable[')

writeModule(resolve(REBUILD, 'src/breaks/generated/blink-break-tables.ts'), `// Generated by rebuild/tools/gen-blink-data.ts from rebuild/data/blink. Do not edit.
// Chrome 153.0.8010.48 icudtl.dat (sha256 a3c6d782…), ICU 78.2, Unicode 17. Entries keep their ICU DataHeader.

export type BlinkBreakTable = ${tables.map(t => `'${t}'`).join(' | ')}

export const blinkBreakTableBase64: Record<BlinkBreakTable, string> = {
${lines.join('\n')}
}

// kFastLineBreakTable for U+0021..U+00FF pairs (223 rows x 28 bytes, bit (b - 0x21) % 8 of byte (b - 0x21) / 8 in row
// a - 0x21), generated by character_property_data_generator.cc over the same icudtl.dat. sha256 of the header:
// ${header.sha256}
export const blinkLinePairsBase64 = '${base64(pairs)}'
`)
