// Generates src/breaks/generated/webkit-break-tables.ts from rebuild/data/webkit (macOS 27.0 26A428 libicucore 78.1
// tables dumped with ubrk_getBinaryRules, and WebKit 7625.1.29.11.27's BreakablePositions pair table). Every input is
// checked against data/webkit/FILES.tsv.
// usage: bun rebuild/tools/gen-webkit-data.ts
//
// The WebKit port extends this file when it needs more WebKit data: classify() is code to port verbatim, and the
// keep-all punctuation set, the CLDR delimiters behind Apple's quote overrides, and General_Category for canBreakBefore
// live in data/webkit (specs/webkit-text.md §5.4, specs/webkit-canvas.md §2.6).
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { DATA, REBUILD, base64, parsePairBitmap, readVerified, writeModule } from './gen-shared.ts'

const shaByPath = new Map<string, string>()
const files = readFileSync(resolve(DATA, 'webkit/FILES.tsv'), 'utf8').trim().split('\n')
for (let i = 0; i < files.length; i++) {
  const [path, , sha] = files[i]!.split('\t')
  shaByPath.set(path!.replace(/^\.\//, ''), sha!)
}

function verified(path: string): Uint8Array {
  const sha = shaByPath.get(path)
  if (sha === undefined) throw new Error(`data/webkit/FILES.tsv has no ${path}`)
  return readVerified(resolve(DATA, 'webkit', path), sha)
}

// The 9 distinct binaries ubrk_open loads on macOS 27, identified from their rule source (specs/webkit-canvas.md §2.5).
const tables: Array<[string, string]> = [
  ['line', 'ac36fb0a8ca06abdd6c91750b3df6c2d90ea89fc27dfedc82e0bf9f7f6e4d001'],
  ['line_loose', 'e4895a01adfb94081be08631ae2271959c0d908d4abf8eacf5bf491138d32828'],
  ['line_normal', '65a4db3a86fbb9d364d5b725213c3402a23e774d0a8e312fd1de0c757266f74b'],
  ['line_cj', '7ef71178db96ab1f697fdfb726bc6e4f00b1bb849f4bc5cc5563c2c01dd01ddd'],
  ['line_normal_cj', '9734e512ac7503d767e72f6aaf4e89db93fa3945873c35f06054013a4f1dabcc'],
  ['line_loose_cj', '93b2373cd26cf6d8b09deffca42a92fe8b1dffedc7dfc5cd104387f94ab2e7be'],
  ['char', 'fe6dbecf6da020b1a6b12fb9e764676769256cc94342ac0ee14605849a75af83'],
]

const lines: string[] = []
for (let i = 0; i < tables.length; i++) {
  const [name, sha] = tables[i]!
  const bytes = verified(`icu-macos27-libicucore/brk/${sha}.brk`)
  lines.push(`  // brk/${sha}.brk: ${bytes.length} bytes`)
  lines.push(`  ${name}: '${base64(bytes)}',`)
}

const inc = new TextDecoder().decode(verified('breakable-positions/linebreak_table.inc'))
const pairs = parsePairBitmap(inc, 'webkitBreakTable')

writeModule(resolve(REBUILD, 'src/breaks/generated/webkit-break-tables.ts'), `// Generated by rebuild/tools/gen-webkit-data.ts from rebuild/data/webkit. Do not edit.
// macOS 27.0 (26A428) /usr/lib/libicucore.A.dylib, u_getVersion 78.1, Unicode 17, CLDR 48. Tables have no DataHeader.

export type WebKitBreakTable = ${tables.map(t => `'${t[0]}'`).join(' | ')}

export const webkitBreakTableBase64: Record<WebKitBreakTable, string> = {
${lines.join('\n')}
}

// LineBreakTable::breakTable, BreakablePositions.cpp:39-267 at WebKit-7625.1.29.11.27: U+0021..U+00FF pairs
// (223 rows x 28 bytes, bit (after - 0x21) % 8 of byte (after - 0x21) / 8 in row before - 0x21).
export const webkitLinePairsBase64 = '${base64(pairs)}'
`)
