// Generates src/engines/webkit/generated/fonts.ts, what WebKit's font selection reads that Canvas can't be asked:
// - the family Core Text names for a CSS generic family under a language, from rebuild/data/webkit/coretext-macos27/
//   css-families.tsv (macOS 27.0 26A428, dumped by data/webkit/tools/ct-css-families.m over every system locale identifier),
//   with WebKit's rules applied: a reserved name with a leading '.' isn't used and the settings' family stands
//   (FontDescriptionCocoa.cpp:77-118), Monaco becomes Courier (SystemFontDatabaseCoreText.cpp:352-365). A family equal to the
//   settings' family (UnifiedWebPreferences.yaml: Times, Helvetica, Apple Chancery, Papyrus, Courier) is left out too: the
//   keyword already resolves to it in Canvas. A language is kept only where its answer differs from its parent's, the
//   identifier less its last subtag;
// - Emoji_Presentation from ICU 78.2's ppucd.txt (FontCascade::resolveEmojiPolicy, FontCascadeCoreText.cpp:473-523).
// usage: bun rebuild/tools/gen-webkit-fonts.ts
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { BROWSER_ENGINES, DATA, REBUILD, readVerified, writeModule } from './gen-shared.ts'
import { PPUCD_PATH, PPUCD_SHA256, forEachPpucdRange } from './ppucd.ts'

const TABLE = 'coretext-macos27/css-families.tsv'
const files = readFileSync(resolve(DATA, 'webkit/FILES.tsv'), 'utf8').trim().split('\n')
let tableSha: string | null = null
for (let i = 0; i < files.length; i++) {
  const [path, , sha] = files[i]!.split('\t')
  if (path === `./${TABLE}`) tableSha = sha!
}
if (tableSha === null) throw new Error(`data/webkit/FILES.tsv has no ${TABLE}`)
const rows = new TextDecoder().decode(readVerified(resolve(DATA, 'webkit', TABLE), tableSha)).trim().split('\n')

const GENERICS = ['serif', 'sans-serif', 'cursive', 'fantasy', 'monospace']
const SETTINGS = ['Times', 'Helvetica', 'Apple Chancery', 'Papyrus', 'Courier']
if (rows[0] !== `language\t${GENERICS.join('\t')}`) throw new Error(`unexpected header in ${TABLE}`)

// language (lower case) -> the five families, '' where the keyword stands.
const answers = new Map<string, string[]>()
for (let i = 1; i < rows.length; i++) {
  const fields = rows[i]!.split('\t')
  const families: string[] = []
  for (let k = 0; k < GENERICS.length; k++) {
    let family = fields[k + 1] ?? ''
    if (k === 4 && family.toLowerCase() === 'monaco') family = 'Courier'
    families.push(family.startsWith('.') || family === SETTINGS[k] ? '' : family)
  }
  answers.set(fields[0]!.toLowerCase(), families)
}

function parentOf(language: string): string {
  const cut = language.lastIndexOf('-')
  return cut < 0 ? '' : language.slice(0, cut)
}

// The root is what Core Text answers for a language it has no entry of its own for: 'und'.
const root = answers.get('und')
if (root === undefined) throw new Error(`${TABLE} has no und row`)
function resolved(language: string, kept: Map<string, string[]>): string[] {
  for (let at = language; at !== ''; at = parentOf(at)) {
    const found = kept.get(at)
    if (found !== undefined) return found
  }
  return root!
}

const kept = new Map<string, string[]>()
const languages = [...answers.keys()].sort((a, b) => a.split('-').length - b.split('-').length || (a < b ? -1 : 1))
for (let i = 0; i < languages.length; i++) {
  const language = languages[i]!
  if (language === 'und') continue
  const own = answers.get(language)!
  if (resolved(parentOf(language), kept).join('\t') !== own.join('\t')) kept.set(language, own)
}
for (let i = 0; i < languages.length; i++) {
  if (resolved(languages[i]!, kept).join('\t') !== answers.get(languages[i]!)!.join('\t')) throw new Error(`the kept languages don't give ${languages[i]} its answer`)
}

const names: string[] = ['']
const indexOf = (name: string): number => {
  let index = names.indexOf(name)
  if (index < 0) index = names.push(name) - 1
  return index
}
const lines: string[] = []
lines.push(`  '': [${root.map(indexOf).join(', ')}],`)
for (const [language, families] of kept) lines.push(`  '${language}': [${families.map(indexOf).join(', ')}],`)

const ppucd = resolve(BROWSER_ENGINES, PPUCD_PATH)
readVerified(ppucd, PPUCD_SHA256)
const emoji: Array<[number, number]> = []
const found: Array<[number, number]> = []
await forEachPpucdRange(ppucd, range => {
  if (range.props.has('EPres')) found.push([range.first, range.last])
})
found.sort((a, b) => a[0] - b[0])
for (let i = 0; i < found.length; i++) {
  const previous = emoji[emoji.length - 1]
  if (previous !== undefined && previous[1] + 1 === found[i]![0]) previous[1] = found[i]![1]
  else emoji.push([found[i]![0], found[i]![1]])
}

writeModule(resolve(REBUILD, 'src/engines/webkit/generated/fonts.ts'), `// Generated by rebuild/tools/gen-webkit-fonts.ts from data/webkit/${TABLE} (sha256 ${tableSha}; Core Text of macOS 27.0
// 26A428, ${answers.size} languages) and ICU 78.2 ppucd.txt (sha256 ${PPUCD_SHA256}). Do not edit.
// webkitGenericFamilies: per language in lower case, indices into webkitGenericFamilyNames for serif, sans-serif, cursive,
// fantasy and monospace; 0 where the keyword resolves as it does without a locale. A language without an entry takes its
// parent's, the identifier less its last subtag, and '' at the end.
export const webkitGenericFamilyNames: readonly string[] = ${JSON.stringify(names)}
export const webkitGenericFamilies: Readonly<Record<string, readonly number[]>> = {
${lines.join('\n')}
}
// Emoji_Presentation, flat inclusive ranges in code point order.
export const webkitEmojiPresentationRanges: readonly number[] = [${emoji.map(r => `0x${r[0].toString(16)}, 0x${r[1].toString(16)}`).join(', ')}]
`)
