// Generates src/breaks/generated/gecko-break-data.ts from Firefox 156's baked ICU4X segmenter data
// (firefox-156.0/intl/icu_segmenter_data/data, icu4x commit 3579f233, CLDR 48, icuexport release-78.1). Each file is
// checked against rebuild/data/gecko/segmenter-data-sha256.json.
// usage: bun rebuild/tools/gen-gecko-data.ts
//
// A data file is databake output: RuleBreakData { property_table: CodePointTrie::from_parts(header, index:
// ZeroVec<u16>, data: ZeroVec<u8>, error_value: u8), break_state_table: ZeroVec<u8>, ... } (icu_segmenter 2.1.2
// src/provider/mod.rs:151-180). The parser follows the groundwork's runtime-parity/gecko/tools/gen-line-data.ts.
//
// The Gecko port extends this file when it needs more Firefox data (the LSTM models for Thai, Lao, Khmer and Burmese are
// segmenter_lstm_auto_v1.rs.data; DESIGN.md §6 explains why the first port uses the running Firefox's Intl.Segmenter).
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { BROWSER_ENGINES, DATA, REBUILD, base64, readVerified, writeModule } from './gen-shared.ts'
import { PPUCD_PATH, PPUCD_SHA256, forEachPpucdRange } from './ppucd.ts'

type HashEntry = { file: string; bytes: number; sha256_firefox156: string }
const hashes = JSON.parse(readFileSync(resolve(DATA, 'gecko/segmenter-data-sha256.json'), 'utf8')) as { files: HashEntry[] }
const SOURCE = resolve(BROWSER_ENGINES, 'firefox-156.0/intl/icu_segmenter_data/data')

function parseByteString(literal: string): Uint8Array {
  const bytes: number[] = []
  for (let i = 0; i < literal.length; i++) {
    const c = literal[i]!
    if (c !== '\\') { bytes.push(c.charCodeAt(0)); continue }
    const e = literal[++i]!
    if (e === 'x') { bytes.push(parseInt(literal.slice(i + 1, i + 3), 16)); i += 2 }
    else if (e === '0') bytes.push(0)
    else if (e === 'n') bytes.push(10)
    else if (e === 'r') bytes.push(13)
    else if (e === 't') bytes.push(9)
    else if (e === '\\' || e === '"' || e === "'") bytes.push(e.charCodeAt(0))
    else throw new Error('unknown escape \\' + e)
  }
  return new Uint8Array(bytes)
}

function ruleData(file: string): string {
  let hash: HashEntry | undefined
  for (let i = 0; i < hashes.files.length; i++) if (hashes.files[i]!.file === file) hash = hashes.files[i]!
  if (hash === undefined) throw new Error(`segmenter-data-sha256.json has no ${file}`)
  const text = new TextDecoder().decode(readVerified(resolve(SOURCE, file), hash.sha256_firefox156))
  if (!/trie_type : icu :: collections :: codepointtrie :: TrieType :: Small/.test(text)) throw new Error(`${file}: expected a small trie`)
  if (!/\) \} , 0u8\) \} , break_state_table/.test(text)) throw new Error(`${file}: expected trie error value 0u8`)
  const literals = [...text.matchAll(/b"((?:[^"\\]|\\.)*)"/g)].map(m => parseByteString(m[1]!))
  const [index, data, states] = literals as [Uint8Array, Uint8Array, Uint8Array]
  const num = (name: string): number => {
    const m = text.match(new RegExp(name + ' : (\\d+)u'))
    if (m === null) throw new Error(`${file}: missing ${name}`)
    return Number(m[1])
  }
  const propertyCount = num('property_count')
  if (index.length % 2 !== 0) throw new Error(`${file}: odd index length`)
  if (states.length !== propertyCount * propertyCount) throw new Error(`${file}: state table is not property_count squared`)
  const b64 = (bytes: Uint8Array) => Buffer.from(bytes).toString('base64')
  return `{
  // ${file}: sha256 ${hash.sha256_firefox156}
  highStart: ${num('high_start')},
  propertyCount: ${propertyCount},
  lastCodepointProperty: ${num('last_codepoint_property')},
  sotProperty: ${num('sot_property')},
  eotProperty: ${num('eot_property')},
  complexProperty: ${num('complex_property')},
  trieIndexBase64: '${b64(index)}',
  trieDataBase64: '${b64(data)}',
  breakStatesBase64: '${b64(states)}',
}`
}

writeModule(resolve(REBUILD, 'src/breaks/generated/gecko-break-data.ts'), `// Generated by rebuild/tools/gen-gecko-data.ts from Firefox 156.0's intl/icu_segmenter_data. Do not edit.
// icu4x commit 3579f233, icuexport release-78.1, CLDR 48. Line classes are icu_segmenter 2.1.2 line.rs:20-128.
import type { Icu4xRuleDataSource } from '../icu4x.js'

export const geckoLineBreakData: Icu4xRuleDataSource = ${ruleData('segmenter_break_line_v1.rs.data')}

export const geckoGraphemeData: Icu4xRuleDataSource = ${ruleData('segmenter_break_grapheme_cluster_v1.rs.data')}
`)

// ---- Character properties the Gecko port reads (src/engines/gecko/generated/props.ts) ----
//
// Gecko reads these through nsUnicodeProperties and intl::UnicodeProperties, which call ICU (u_charType,
// u_getIntPropertyValue, u_hasBinaryProperty): General_Category (IsClusterExtender, IsAlphanumeric, East Asian
// punctuation, formatting controls), East_Asian_Width (segment-break removal, nsUnicharUtils.cpp:498-524), Script and
// Script_Extensions (gfxScriptItemizer, Hangul, cursive scripts), Emoji (UnicodeProperties.h:205-218),
// Default_Ignorable_Code_Point (nsTextFrameUtils.cpp:106-129), Bidi_Mirrored and the mirror glyph (gfxScriptItemizer
// paired punctuation). Joining_Type and the emoji presentation properties feed the port's joined-edge flag and the
// Apple Color Emoji cluster rule. The source is ICU 78.2's ppucd.txt (Unicode 17), the same data tools/ppucd.ts reads.
const GC = ['Cn', 'Lu', 'Ll', 'Lt', 'Lm', 'Lo', 'Mn', 'Mc', 'Me', 'Nd', 'Nl', 'No', 'Pc', 'Pd', 'Ps', 'Pe', 'Pi', 'Pf', 'Po', 'Sm', 'Sc', 'Sk', 'So', 'Zs', 'Zl', 'Zp', 'Cc', 'Cf', 'Cs', 'Co']
const EA = ['N', 'A', 'H', 'F', 'Na', 'W']
const JT = ['U', 'C', 'D', 'L', 'R', 'T']
const ppucdPath = resolve(BROWSER_ENGINES, PPUCD_PATH)
readVerified(ppucdPath, PPUCD_SHA256)
const packed = new Uint32Array(0x110000)
const scxOf = new Int32Array(0x110000).fill(-1)
const scripts: string[] = ['Zzzz']
const scxLists: string[] = []
const mirrors: number[] = []
const indexOf = (list: string[], value: string): number => {
  let i = list.indexOf(value)
  if (i < 0) { i = list.length; list.push(value) }
  return i
}
const enumIndex = (list: string[], value: string | undefined, name: string): number => {
  const i = list.indexOf(value ?? '')
  if (i < 0) throw new Error(`unknown ${name} value ${value}`)
  return i
}
await forEachPpucdRange(ppucdPath, range => {
  const p = range.props
  const sc = indexOf(scripts, p.get('sc') ?? 'Zzzz')
  if (sc > 255) throw new Error('more than 256 scripts')
  const value = enumIndex(GC, p.get('gc'), 'gc') | enumIndex(EA, p.get('ea'), 'ea') << 5 | enumIndex(JT, p.get('jt'), 'jt') << 8 |
    (p.has('Emoji') ? 1 << 11 : 0) | (p.has('EPres') ? 1 << 12 : 0) | (p.has('ExtPict') ? 1 << 13 : 0) |
    (p.has('DI') ? 1 << 14 : 0) | (p.has('Bidi_M') ? 1 << 15 : 0) | (p.has('EMod') ? 1 << 16 : 0) | sc << 17
  const scx = p.get('scx')
  const scxIndex = scx === undefined || scx === '<script>' ? -1 : indexOf(scxLists, scx)
  for (let cp = range.first; cp <= range.last; cp++) {
    packed[cp] = value
    scxOf[cp] = scxIndex
  }
  const bmg = p.get('bmg')
  if (p.get('gc') === 'Ps' && p.has('Bidi_M') && bmg !== undefined && bmg !== '<code point>') {
    for (let cp = range.first; cp <= range.last; cp++) mirrors.push(cp, parseInt(bmg, 16))
  }
})
// [start, value] u32 pairs where the value changes; the last range ends at U+10FFFF.
function runs(values: Uint32Array | Int32Array): Uint8Array {
  const out: number[] = []
  for (let cp = 0; cp < values.length; cp++) if (cp === 0 || values[cp] !== values[cp - 1]) out.push(cp, values[cp]! >>> 0)
  return new Uint8Array(new Uint32Array(out).buffer)
}
writeModule(resolve(REBUILD, 'src/engines/gecko/generated/props.ts'), `// Generated by rebuild/tools/gen-gecko-data.ts from ICU 78.2 ppucd.txt (sha256 ${PPUCD_SHA256}). Do not edit.
// propertyRuns: u32 little-endian [start, packed] pairs, packed = gc | ea << 5 | jt << 8 | Emoji << 11 | EPres << 12 |
// ExtPict << 13 | DI << 14 | Bidi_M << 15 | EMod << 16 | script << 17. scriptExtensionRuns: [start, list index or -1].
export const generalCategories: readonly string[] = ${JSON.stringify(GC)}
export const eastAsianWidths: readonly string[] = ${JSON.stringify(EA)}
export const joiningTypes: readonly string[] = ${JSON.stringify(JT)}
export const scriptNames: readonly string[] = ${JSON.stringify(scripts)}
export const scriptExtensionLists: readonly string[] = ${JSON.stringify(scxLists)}
export const propertyRunsBase64 = '${base64(runs(packed))}'
export const scriptExtensionRunsBase64 = '${base64(runs(scxOf))}'
// [opening punctuation, Bidi_Mirroring_Glyph] pairs.
export const openingMirrors: readonly number[] = ${JSON.stringify(mirrors)}
`)
