// Generates src/engines/webkit/generated/joining.ts: Unicode Joining_Type from ICU 78.2's ppucd.txt, the property source
// the other generators read (tools/ppucd.ts). The WebKit port reads it where text is shaped across inline boxes: whether the
// letters at a box edge join decides the context a run is measured in (engines/webkit/lines.ts applyShapingOnRunRange).
// usage: bun rebuild/tools/gen-webkit-joining.ts
import { resolve } from 'node:path'
import { BROWSER_ENGINES, REBUILD, readVerified, writeModule } from './gen-shared.ts'
import { PPUCD_PATH, PPUCD_SHA256, forEachPpucdRange } from './ppucd.ts'

const path = resolve(BROWSER_ENGINES, PPUCD_PATH)
readVerified(path, PPUCD_SHA256)

const found: Array<[number, number, string]> = []
await forEachPpucdRange(path, range => {
  const type = range.props.get('jt') ?? 'U'
  if (type !== 'U') found.push([range.first, range.last, type])
})
found.sort((a, b) => a[0] - b[0])
const ranges: Array<[number, number, string]> = []
for (let i = 0; i < found.length; i++) {
  const [first, last, type] = found[i]!
  if (!'CDLRT'.includes(type)) throw new Error(`unknown Joining_Type ${type} at U+${first.toString(16)}`)
  const previous = ranges[ranges.length - 1]
  if (previous !== undefined && previous[1] + 1 === first && previous[2] === type) previous[1] = last
  else ranges.push([first, last, type])
}

// Per range, in code point order: the gap from the end of the range before it and the range's length less one, in base 36
// with a dot between them, then the type letter.
let packed = ''
let end = -1
for (let i = 0; i < ranges.length; i++) {
  const [first, last, type] = ranges[i]!
  packed += `${(first - end - 1).toString(36)}.${(last - first).toString(36)}${type}`
  end = last
}

writeModule(resolve(REBUILD, 'src/engines/webkit/generated/joining.ts'), `// Generated by rebuild/tools/gen-webkit-joining.ts from ICU 78.2 ppucd.txt (sha256 ${PPUCD_SHA256}). Do not edit.
// Joining_Type other than U (Non_Joining), ${ranges.length} ranges in code point order: the gap from the end of the range before it and
// the range's length less one, in base 36 with a dot between them, then the type (C, D, L, R or T).
export const webkitJoiningTypeRanges = '${packed}'
`)
