// Generates src/engines/gecko/generated/break-data.ts from Firefox 156's baked ICU4X segmenter data
// (firefox-156.0/intl/icu_segmenter_data/data, icu4x commit 3579f233, CLDR 48, icuexport release-78.1). Each file is
// checked against rebuild/data/gecko/segmenter-data-sha256.json.
// usage: bun rebuild/tools/gen-gecko-data.ts
//
// A data file is databake output: RuleBreakData { property_table: CodePointTrie::from_parts(header, index:
// ZeroVec<u16>, data: ZeroVec<u8>, error_value: u8), break_state_table: ZeroVec<u8>, ... } (icu_segmenter 2.1.2
// src/provider/mod.rs:151-180). The parser follows the groundwork's runtime-parity/gecko/tools/gen-line-data.ts.
//
// The Gecko port extends this file when it needs more Firefox data (the LSTM models for Thai, Lao, Khmer and Burmese are
// segmenter_lstm_auto_v1.rs.data; DESIGN.md §6 explains why the first port uses the running Firefox's Intl.Segmenter).
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { BROWSER_ENGINES, DATA, REBUILD, base64, readVerified, writeModule } from './gen-shared.ts'
import { PPUCD_PATH, PPUCD_SHA256, forEachPpucdBlock, forEachPpucdRange, type PpucdRange } from './ppucd.ts'

type HashEntry = { file: string; bytes: number; sha256_firefox156: string }
const hashes = JSON.parse(readFileSync(resolve(DATA, 'gecko/segmenter-data-sha256.json'), 'utf8')) as { files: HashEntry[] }
const SOURCE = resolve(BROWSER_ENGINES, 'firefox-156.0/intl/icu_segmenter_data/data')

function parseByteString(literal: string): Uint8Array {
  const bytes: number[] = []
  for (let i = 0; i < literal.length; i++) {
    const c = literal[i]!
    if (c !== '\\') { bytes.push(c.charCodeAt(0)); continue }
    const e = literal[++i]!
    if (e === 'x') { bytes.push(parseInt(literal.slice(i + 1, i + 3), 16)); i += 2 }
    else if (e === '0') bytes.push(0)
    else if (e === 'n') bytes.push(10)
    else if (e === 'r') bytes.push(13)
    else if (e === 't') bytes.push(9)
    else if (e === '\\' || e === '"' || e === "'") bytes.push(e.charCodeAt(0))
    else throw new Error('unknown escape \\' + e)
  }
  return new Uint8Array(bytes)
}

function ruleData(file: string): string {
  let hash: HashEntry | undefined
  for (let i = 0; i < hashes.files.length; i++) if (hashes.files[i]!.file === file) hash = hashes.files[i]!
  if (hash === undefined) throw new Error(`segmenter-data-sha256.json has no ${file}`)
  const text = new TextDecoder().decode(readVerified(resolve(SOURCE, file), hash.sha256_firefox156))
  if (!/trie_type : icu :: collections :: codepointtrie :: TrieType :: Small/.test(text)) throw new Error(`${file}: expected a small trie`)
  if (!/\) \} , 0u8\) \} , break_state_table/.test(text)) throw new Error(`${file}: expected trie error value 0u8`)
  const literals = [...text.matchAll(/b"((?:[^"\\]|\\.)*)"/g)].map(m => parseByteString(m[1]!))
  const [index, data, states] = literals as [Uint8Array, Uint8Array, Uint8Array]
  const num = (name: string): number => {
    const m = text.match(new RegExp(name + ' : (\\d+)u'))
    if (m === null) throw new Error(`${file}: missing ${name}`)
    return Number(m[1])
  }
  const propertyCount = num('property_count')
  if (index.length % 2 !== 0) throw new Error(`${file}: odd index length`)
  if (states.length !== propertyCount * propertyCount) throw new Error(`${file}: state table is not property_count squared`)
  const b64 = (bytes: Uint8Array) => Buffer.from(bytes).toString('base64')
  return `{
  // ${file}: sha256 ${hash.sha256_firefox156}
  highStart: ${num('high_start')},
  propertyCount: ${propertyCount},
  lastCodepointProperty: ${num('last_codepoint_property')},
  sotProperty: ${num('sot_property')},
  eotProperty: ${num('eot_property')},
  complexProperty: ${num('complex_property')},
  trieIndexBase64: '${b64(index)}',
  trieDataBase64: '${b64(data)}',
  breakStatesBase64: '${b64(states)}',
}`
}

writeModule(resolve(REBUILD, 'src/engines/gecko/generated/break-data.ts'), `// Generated by rebuild/tools/gen-gecko-data.ts from Firefox 156.0's intl/icu_segmenter_data. Do not edit.
// icu4x commit 3579f233, icuexport release-78.1, CLDR 48. Line classes are icu_segmenter 2.1.2 line.rs:20-128.
import type { Icu4xRuleDataSource } from '../../../breaks/icu4x.js'

export const geckoLineBreakData: Icu4xRuleDataSource = ${ruleData('segmenter_break_line_v1.rs.data')}

export const geckoGraphemeData: Icu4xRuleDataSource = ${ruleData('segmenter_break_grapheme_cluster_v1.rs.data')}
`)

// ---- Character properties the Gecko port reads (src/engines/gecko/generated/props.ts) ----
//
// Gecko reads these through nsUnicodeProperties and intl::UnicodeProperties, which call ICU (u_charType,
// u_getIntPropertyValue, u_hasBinaryProperty): General_Category (IsClusterExtender, IsAlphanumeric, East Asian
// punctuation, formatting controls), East_Asian_Width (segment-break removal, nsUnicharUtils.cpp:498-524), Script and
// Script_Extensions (gfxScriptItemizer, Hangul, cursive scripts), Emoji (UnicodeProperties.h:205-218),
// Default_Ignorable_Code_Point (nsTextFrameUtils.cpp:106-129), Bidi_Mirrored and the mirror glyph (gfxScriptItemizer
// paired punctuation). Joining_Type and the emoji presentation properties feed the port's joined-edge flag and the
// Apple Color Emoji cluster rule. The source is ICU 78.2's ppucd.txt (Unicode 17), the same data tools/ppucd.ts reads.
const GC = ['Cn', 'Lu', 'Ll', 'Lt', 'Lm', 'Lo', 'Mn', 'Mc', 'Me', 'Nd', 'Nl', 'No', 'Pc', 'Pd', 'Ps', 'Pe', 'Pi', 'Pf', 'Po', 'Sm', 'Sc', 'Sk', 'So', 'Zs', 'Zl', 'Zp', 'Cc', 'Cf', 'Cs', 'Co']
const EA = ['N', 'A', 'H', 'F', 'Na', 'W']
const JT = ['U', 'C', 'D', 'L', 'R', 'T']
const ppucdPath = resolve(BROWSER_ENGINES, PPUCD_PATH)
readVerified(ppucdPath, PPUCD_SHA256)
const packed = new Uint32Array(0x110000)
const scxOf = new Int32Array(0x110000).fill(-1)
const scripts: string[] = ['Zzzz']
const scxLists: string[] = []
const mirrors: number[] = []
const indexOf = (list: string[], value: string): number => {
  let i = list.indexOf(value)
  if (i < 0) { i = list.length; list.push(value) }
  return i
}
const enumIndex = (list: string[], value: string | undefined, name: string): number => {
  const i = list.indexOf(value ?? '')
  if (i < 0) throw new Error(`unknown ${name} value ${value}`)
  return i
}
const fill = (range: PpucdRange): void => {
  const p = range.props
  const sc = indexOf(scripts, p.get('sc') ?? 'Zzzz')
  if (sc > 255) throw new Error('more than 256 scripts')
  const value = enumIndex(GC, p.get('gc'), 'gc') | enumIndex(EA, p.get('ea'), 'ea') << 5 | enumIndex(JT, p.get('jt'), 'jt') << 8 |
    (p.has('Emoji') ? 1 << 11 : 0) | (p.has('EPres') ? 1 << 12 : 0) | (p.has('ExtPict') ? 1 << 13 : 0) |
    (p.has('DI') ? 1 << 14 : 0) | (p.has('Bidi_M') ? 1 << 15 : 0) | (p.has('EMod') ? 1 << 16 : 0) | sc << 17
  const scx = p.get('scx')
  const scxIndex = scx === undefined || scx === '<script>' ? -1 : indexOf(scxLists, scx)
  for (let cp = range.first; cp <= range.last; cp++) {
    packed[cp] = value
    scxOf[cp] = scxIndex
  }
}
// Block values first: code points no cp or unassigned line names keep them (tools/ppucd.ts forEachPpucdBlock). Outside
// every block the defaults apply, which are index 0 of each table above (gc=Cn, ea=N, jt=U, sc=Zzzz).
await forEachPpucdBlock(ppucdPath, fill)
await forEachPpucdRange(ppucdPath, range => {
  fill(range)
  const p = range.props
  const bmg = p.get('bmg')
  if (p.get('gc') === 'Ps' && p.has('Bidi_M') && bmg !== undefined && bmg !== '<code point>') {
    for (let cp = range.first; cp <= range.last; cp++) mirrors.push(cp, parseInt(bmg, 16))
  }
})
// [start, value] u32 pairs where the value changes; the last range ends at U+10FFFF.
function runs(values: Uint32Array | Int32Array): Uint8Array {
  const out: number[] = []
  for (let cp = 0; cp < values.length; cp++) if (cp === 0 || values[cp] !== values[cp - 1]) out.push(cp, values[cp]! >>> 0)
  return new Uint8Array(new Uint32Array(out).buffer)
}
writeModule(resolve(REBUILD, 'src/engines/gecko/generated/props.ts'), `// Generated by rebuild/tools/gen-gecko-data.ts from ICU 78.2 ppucd.txt (sha256 ${PPUCD_SHA256}). Do not edit.
// propertyRuns: u32 little-endian [start, packed] pairs, packed = gc | ea << 5 | jt << 8 | Emoji << 11 | EPres << 12 |
// ExtPict << 13 | DI << 14 | Bidi_M << 15 | EMod << 16 | script << 17. scriptExtensionRuns: [start, list index or -1].
export const generalCategories: readonly string[] = ${JSON.stringify(GC)}
export const eastAsianWidths: readonly string[] = ${JSON.stringify(EA)}
export const joiningTypes: readonly string[] = ${JSON.stringify(JT)}
export const scriptNames: readonly string[] = ${JSON.stringify(scripts)}
export const scriptExtensionLists: readonly string[] = ${JSON.stringify(scxLists)}
export const propertyRunsBase64 = '${base64(runs(packed))}'
export const scriptExtensionRunsBase64 = '${base64(runs(scxOf))}'
// [opening punctuation, Bidi_Mirroring_Glyph] pairs.
export const openingMirrors: readonly number[] = ${JSON.stringify(mirrors)}
`)

// ---- Likely subtags (src/engines/gecko/generated/likely-subtags.ts) ----
//
// nsLineBreaker decides whether a word's language is Chinese or Japanese through mozilla::intl::Locale::AddLikelySubtags,
// which calls uloc_addLikelySubtags of the ICU Firefox bundles (nsLineBreaker.cpp:659-690, intl/components/src/
// Locale.cpp:765-935). Firefox 156 bundles ICU 78.3 (intl/icu/source/common/unicode/uvernum.h), whose likely subtags are
// the `likely` table of intl/icu/source/data/misc/langInfo.txt: language and region aliases, LSRs encoded as integers
// (lsrnum, decoded by LikelySubtagsData::readLSREncodedStrings, loclikelysubtags.cpp:260-330) and the BytesTrie that
// LikelySubtags::maximize walks. Script codes decode through uscript_getShortName, whose names are the ISO codes in
// uscript.h's UScriptCode comments.
const LANG_INFO = resolve(BROWSER_ENGINES, 'firefox-156.0/intl/icu/source/data/misc/langInfo.txt')
const LANG_INFO_SHA256 = '799bfbd3524d337f85575a27b8a316b1eb93181c2103bdb2fb96b812dc554860'
const USCRIPT_H = resolve(BROWSER_ENGINES, 'firefox-156.0/intl/icu/source/common/unicode/uscript.h')
const USCRIPT_H_SHA256 = '293adf40390583c1c5394d3dc1794ed1669e8356cdf292ca5eaac145a2a5d1e0'

const langInfo = new TextDecoder().decode(readVerified(LANG_INFO, LANG_INFO_SHA256))
const uscript = new TextDecoder().decode(readVerified(USCRIPT_H, USCRIPT_H_SHA256))
const scriptShortNames: string[] = []
for (const m of uscript.matchAll(/USCRIPT_[A-Z_0-9]+\s*=\s*(\d+)\s*,\s*\/\*\s*([A-Z][a-z]{3})\s*\*\//g)) {
  const code = Number(m[1])
  if (scriptShortNames[code] !== undefined) throw new Error(`uscript.h: code ${code} twice`)
  scriptShortNames[code] = m[2]!
}
const likelyFrom = langInfo.indexOf('    likely{')
const likelyTo = langInfo.indexOf('\n    match{')
if (likelyFrom < 0 || likelyTo < likelyFrom) throw new Error('langInfo.txt: no likely table')
const likelyTable = langInfo.slice(likelyFrom, likelyTo)
// The body of `name{ ... }` or `name:type{ ... }` inside the likely table.
function section(name: string): string {
  const m = new RegExp(`\\n        ${name}(?::[a-z]+)?\\{\\n([\\s\\S]*?)\\n        \\}`).exec(likelyTable)
  if (m === null) throw new Error(`langInfo.txt: no likely/${name}`)
  return m[1]!
}
const quoted = (body: string): string[] => [...body.matchAll(/"([^"]*)"/g)].map(m => m[1]!)
const languageAliasPairs = quoted(section('languageAliases'))
const regionAliasPairs = quoted(section('regionAliases'))
const m49 = quoted(section('m49'))
const lsrnum = section('lsrnum').split(/[\s,]+/).filter(s => s.length > 0).map(s => Number(s) | 0)
const trieHex = section('trie').replace(/\s+/g, '')
if (languageAliasPairs.length % 2 !== 0 || regionAliasPairs.length % 2 !== 0 || trieHex.length % 2 !== 0) throw new Error('langInfo.txt: malformed likely table')
const trieBytes = new Uint8Array(trieHex.length / 2)
for (let i = 0; i < trieBytes.length; i++) trieBytes[i] = parseInt(trieHex.slice(2 * i, 2 * i + 2), 16)
const decodeLanguage = (encoded: number): string => {
  if (encoded === 0) return ''
  if (encoded === 1) return 'skip'
  const e = (encoded & 0xffffff) % (27 * 27 * 27)
  const letter = (k: number): string => String.fromCharCode(0x61 + k - 1)
  const two = letter(e % 27) + letter(Math.floor(e / 27) % 27)
  return Math.floor(e / (27 * 27)) === 0 ? two : two + letter(Math.floor(e / (27 * 27)))
}
const decodeScript = (encoded: number): string => {
  if (encoded === 0) return ''
  if (encoded === 1) return 'script'
  return scriptShortNames[(encoded >> 24) & 0xff] ?? ''
}
const decodeRegion = (encoded: number): string => {
  if (encoded === 0 || encoded === 1) return ''
  const e = Math.floor((encoded & 0xffffff) / (27 * 27 * 27)) % (27 * 27)
  if (e < 27) {
    const code = m49[e]
    if (code === undefined) throw new Error(`langInfo.txt: m49 index ${e}`)
    return code
  }
  return String.fromCharCode(0x41 + (e % 27) - 1, 0x41 + (Math.floor(e / 27) % 27) - 1)
}
const lsrs: string[] = []
for (let i = 0; i < lsrnum.length; i++) lsrs.push(`${decodeLanguage(lsrnum[i]!)} ${decodeScript(lsrnum[i]!)} ${decodeRegion(lsrnum[i]!)}`)
// ulocimp_getSubtags turns a 3-letter language or region code into its 2-letter equivalent through uloc.cpp's parallel
// ISO 639 and ISO 3166 tables, two nullptr-terminated lists each (uloc.cpp:103-470, _findIndex :1177-1195, _getLanguage
// :1219-1271, _getRegion :1305-1343).
const ULOC_CPP = resolve(BROWSER_ENGINES, 'firefox-156.0/intl/icu/source/common/uloc.cpp')
const ULOC_CPP_SHA256 = 'bb47812d836dbfcbb2b7c858ff205b330c1033a273e0864a71f0083158e3717f'
const uloc = new TextDecoder().decode(readVerified(ULOC_CPP, ULOC_CPP_SHA256))
function ulocTable(name: string): Array<string | null> {
  const from = uloc.indexOf(`constexpr const char* ${name}[] = {`)
  if (from < 0) throw new Error(`uloc.cpp: no table ${name}`)
  const body = uloc.slice(uloc.indexOf('{', from) + 1, uloc.indexOf('};', from)).replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/[^\n]*/g, '')
  const out: Array<string | null> = []
  for (const m of body.matchAll(/"([^"]*)"|nullptr/g)) out.push(m[1] ?? null)
  if (out.filter(v => v === null).length !== 2) throw new Error(`uloc.cpp: ${name} is not two nullptr-terminated lists`)
  return out
}
// [three-letter, two-letter] pairs where _findIndex's first match differs from its equivalent.
function threeToTwo(twoName: string, threeName: string): string[] {
  const two = ulocTable(twoName)
  const three = ulocTable(threeName)
  if (two.length !== three.length) throw new Error(`uloc.cpp: ${twoName} and ${threeName} differ in length`)
  const seen = new Set<string>()
  const pairs: string[] = []
  for (let i = 0; i < three.length; i++) {
    const code = three[i]!
    if (code === null || seen.has(code)) continue
    seen.add(code)
    if (two[i] === null) throw new Error(`uloc.cpp: ${twoName} and ${threeName} don't align at ${i}`)
    if (two[i] !== code) pairs.push(code, two[i]!)
  }
  return pairs
}
const languageCodes3 = threeToTwo('LANGUAGES', 'LANGUAGES_3')
const countryCodes3 = threeToTwo('COUNTRIES', 'COUNTRIES_3')
writeModule(resolve(REBUILD, 'src/engines/gecko/generated/likely-subtags.ts'), `// Generated by rebuild/tools/gen-gecko-data.ts from Firefox 156.0's bundled ICU 78.3 data. Do not edit.
// intl/icu/source/data/misc/langInfo.txt (sha256 ${LANG_INFO_SHA256}), table likely; script names from
// intl/icu/source/common/unicode/uscript.h (sha256 ${USCRIPT_H_SHA256}); 3-letter codes from
// intl/icu/source/common/uloc.cpp (sha256 ${ULOC_CPP_SHA256}).
// Aliases and codes are [from, to] pairs. Each LSR is "language script region" (any part may be empty), joined by ';'.
export const likelyLanguageCodes3: readonly string[] = ${JSON.stringify(languageCodes3)}
export const likelyCountryCodes3: readonly string[] = ${JSON.stringify(countryCodes3)}
export const likelyLanguageAliases: readonly string[] = ${JSON.stringify(languageAliasPairs)}
export const likelyRegionAliases: readonly string[] = ${JSON.stringify(regionAliasPairs)}
export const likelyLsrs = '${lsrs.join(';')}'
export const likelyTrieBase64 = '${base64(trieBytes)}'
`)
