// Original prose for the editorial reflow demo, inspired by the sea.

export const CHAPTER_LABEL = 'Chapter One'
export const CHAPTER_TITLE = 'The Waters Beyond the Reef'

export const PULLQUOTE_TEXT = 'The sea does not reward those who are too anxious, too greedy, or too impatient. One must lie empty, open, choiceless as a beach — waiting for a gift from the sea.'

export const BODY_TEXT = `\
He went out alone in the mornings when the light was still gray and the harbor air carried the smell of salt and diesel and yesterday's catch drying on the concrete. The skiff was small and the paint had long since given way to bare wood in places, but it moved through the water the way it always had, with a low steady purpose that did not need explaining. He kept the oars shipped until he was past the breakwater, then set the sail and let the offshore breeze carry him toward the deep blue line where the shelf dropped away and the current ran strong and cold from the north.

For eighty-four days he had gone out and come back with nothing. The other fishermen had stopped talking about it. At first they had offered advice, then sympathy, then silence. The boy who used to help him carry the lines and the gaff and the big wicker basket had been told by his parents to fish with someone else, someone luckier, and the old man had not argued. He understood luck. He had lived long enough to know that it was not a thing you could hold or summon, only a thing you could be ready for when it arrived.

The water beyond the reef was a different country. The green shallows gave way to a blue so deep it looked almost purple in the early light, and the bottom fell away to places where no anchor could reach. Out here the big fish moved in patterns that followed the current and the temperature and the phases of the moon, and a man who paid attention could sometimes read those patterns the way a farmer reads the sky before a storm. The old man had been reading this water for fifty years. He knew where the marlin traveled in September and where the dorado schooled when the water warmed in June. He knew which birds meant baitfish below and which were just riding the thermals with empty bellies.

This morning he felt something different. Not confidence exactly, and not hope, which he had learned to distrust as a younger man. It was more like a quiet attention, a sense that the world was about to show him something if he could stay patient and keep his hands steady on the line. He set out four lines at different depths, each baited with fresh sardines he had caught the evening before in the shallows near the river mouth. The sardines were bright and firm and he had kept them alive in a bucket of seawater until the last moment, because a fresh bait moves differently in the current and the big fish know the difference.

The sun climbed and the gray light turned gold and then white. The skiff rocked gently in the long Atlantic swell. He sat in the stern with his back against the transom and his feet braced against a thwart and he watched the lines where they entered the water, four thin cords connecting him to whatever moved below. He had no radio and no electronics and no engine. He had a water jug and a piece of bread wrapped in newspaper and a knife with a wooden handle that his father had given him before the war. These were the tools of his trade and they had always been enough.

Around midmorning the line on the starboard quarter dipped sharply, then went slack, then dipped again. He watched it without moving. A premature strike would lose the fish. He let the line run through his fingers and felt the weight on the other end, felt the way it moved — not the quick darting pull of a small fish but the slow heavy draw of something large turning in the deep water. He let it take more line. He let it think it was free. Then, when he felt the tension change and knew the hook had set, he leaned back and struck hard with both hands and the line went taut and sang in the air like a wire.

The fish did not jump. The great ones rarely do at first. Instead it simply began to move, pulling the skiff behind it with a force that was steady and enormous and unhurried, the way a river pulls at a bridge piling. The old man braced his feet and wrapped the line once around the bitt and held on. The skiff slid forward through the water, leaving a wake like a motorboat, and the harbor and the breakwater and the town fell away behind him until there was nothing but blue water in every direction and the sun overhead and the line going down into the dark.

He was not afraid. Fear was something that lived in the spaces between action, in the waiting and the wondering, and now there was no space for it. There was only the fish and the line and the sea and the ancient simple negotiation between a man and the thing he has come to find. The line cut into his hands and he shifted his grip and held on. He had nowhere else to be.

The hours passed. The fish pulled south and then east and then south again, following some deep channel or temperature line that the old man could not see but could feel in the angle of the rope and the speed of the drift. He drank water sparingly and ate half the bread and saved the rest. The sun moved across the sky and the shadows shortened and then lengthened again and the light began to turn amber and then copper and then the deep red-gold of the tropical evening.

Still the fish pulled. The old man's hands were raw now and his back ached and his shoulders burned from the constant tension, but he did not let go. He talked to the fish sometimes, quietly, the way you might talk to a worthy opponent in a game that has gone on longer than either of you expected. He told it that he respected it and that he was sorry for what he had to do and that he hoped it understood. The fish did not answer, but it did not need to. They understood each other in the way that only old enemies can, through the language of resistance and endurance and the shared knowledge that this would end the way all such contests end, with one of them giving way.

The stars came out. The wind dropped. The sea went flat and black and the skiff sat motionless except for the slow forward creep of the line pulling it south. The old man wrapped the line around his waist and leaned back and tried to rest. He could feel the fish still moving below him, still pulling, still alive, and he marveled at the strength of it. Somewhere down in that black water, in the cold and the pressure and the dark, a great silver thing was swimming with a hook in its jaw, towing a wooden boat and an old man across the surface of the sea, and it had not stopped or slowed since midmorning.

He slept in fragments, five minutes at a time, and each time he woke the line was still taut and the stars had shifted slightly in the sky. Toward dawn the pulling eased. Not stopped, but eased, the way a runner's pace slows in the last miles of a long race. The old man straightened up and took in line, hand over hand, slowly, carefully, not forcing it, letting the fish set the pace of its own surrender. The line came in wet and heavy and coiled at his feet in loose figure-eights and he could feel the fish rising, coming up out of the deep water into the warmer layers near the surface.

Then he saw it. A flash of silver in the dark water, then a shape, then the whole impossible length of it rolling just below the surface, longer than the skiff, wider than the old man could reach with both arms. It was the biggest fish he had ever seen. It was the biggest fish anyone in the harbor had ever seen. It moved with a dignity that made him want to cut the line and let it go, and he almost did, but he did not, because this was the work and the work was what remained when everything else had been taken away.

He brought it alongside just as the sun broke the horizon, and the sea around the skiff turned from black to deep blue to the pale translucent green of the shallows, though they were miles from any shallow water. The fish lay on its side, exhausted, its great eye looking up at the old man with an expression that was not fear and not anger but something closer to recognition. The old man looked back. Then he picked up the gaff with his bleeding hands and did what he had come out here to do.

The journey home took the rest of that day and most of the night. He rigged a tow line and lashed the fish to the side of the skiff and set the sail for the harbor. The wind had shifted to the west and he had to tack, and the fish was heavy and the skiff rode low in the water and every wave washed over the gunwale and he had to bail with a coffee can while steering with his knee. But he kept going because that is what you do. You go out and you find the thing and you bring it back. That is the whole story. Everything else is just detail.

When he reached the harbor it was nearly dawn again and the lights were on in the coffee shop by the dock and a few early risers were standing on the seawall looking out at the water. They saw the skiff first, sitting low and moving slowly, and then they saw what was lashed alongside it, and they stopped talking. One of them went to get the boy, and when the boy came running down to the dock the old man was tying off the bowline with hands that could barely close around the rope.

The boy did not say anything. He just stood there and looked at the fish and then looked at the old man and then went aboard and started cleaning up the lines and the gear the way he always used to do. The old man sat on the dock with his feet hanging over the water and watched the sunrise paint the harbor gold. He was very tired and his hands hurt and he knew he would need to sleep soon, but for now he just sat and breathed and let the morning settle around him like a blanket.

Tomorrow he would go out again. That was the thing about the sea. It was always there, and it always had more to give, and all it asked in return was that you be willing to go out far enough and stay out long enough and hold on tight enough. The old man had been doing this for fifty years and he would do it for as long as his body allowed. Not because he had to and not because he wanted to but because it was the truest thing he knew.\
`
