// Writes rebuild/tests/rules.json from the 2026-09-16 rule catalogue and the stage-1 changes.
//   bun rebuild/tests/import-rules.ts [--catalogue=.artifacts/research-20260916/tentpoles/rules/rules.json] [--changes=rebuild/tests/rule-changes.json]
import { writeFileSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { REGISTRY_PATH, type Registry, type RuleKind, type RuleRecord } from './registry.ts'

const REPO = resolve(import.meta.dir, '../..')
type CatalogueRule = { id: string; engine: RuleRecord['engine']; area: string; kind: RuleKind; statement: string; source: string; probes: string[]; tests: string[]; audit: string | null }
type Changes = {
  note: string
  removed: Array<{ id: string; reason: string; replacedBy: string[] }>
  reclassified: Array<{ id: string; kind: RuleKind; statement: string; declaredBy: string }>
  added: Array<Omit<RuleRecord, 'audit' | 'status' | 'replacedBy'>>
}

const args = new Map(process.argv.slice(2).map(arg => {
  const match = /^--([a-z-]+)=(.*)$/s.exec(arg)
  if (match === null) throw new Error(`Unknown argument ${arg}`)
  return [match[1]!, match[2]!] as const
}))
const cataloguePath = resolve(REPO, args.get('catalogue') ?? '.artifacts/research-20260916/tentpoles/rules/rules.json')
const changesPath = resolve(REPO, args.get('changes') ?? 'rebuild/tests/rule-changes.json')
const catalogue = (JSON.parse(readFileSync(cataloguePath, 'utf8')) as { generatedAt: string; rules: CatalogueRule[] })
const changes = JSON.parse(readFileSync(changesPath, 'utf8')) as Changes

const byId = new Map<string, RuleRecord>()
for (const rule of catalogue.rules) {
  byId.set(rule.id, {
    id: rule.id, engine: rule.engine, area: rule.area, kind: rule.kind, statement: rule.statement, source: rule.source,
    probes: rule.probes, tests: rule.tests, audit: rule.audit, status: 'current', replacedBy: [], declaredBy: 'catalogue 2026-09-16',
  })
}
for (const change of changes.removed) {
  const rule = byId.get(change.id)
  if (rule === undefined) throw new Error(`removed ${change.id} is not in the catalogue`)
  rule.status = 'removed'
  rule.replacedBy = change.replacedBy
  rule.statement = `${rule.statement} [removed: ${change.reason}]`
}
for (const change of changes.reclassified) {
  const rule = byId.get(change.id)
  if (rule === undefined) throw new Error(`reclassified ${change.id} is not in the catalogue`)
  rule.kind = change.kind
  rule.statement = change.statement
  rule.declaredBy = change.declaredBy
}
for (const added of changes.added) {
  if (byId.has(added.id)) throw new Error(`added ${added.id} is already in the catalogue`)
  byId.set(added.id, { ...added, audit: null, status: 'current', replacedBy: [] })
}
for (const rule of byId.values()) {
  for (const id of rule.replacedBy) if (!byId.has(id)) throw new Error(`${rule.id} is replaced by unknown ${id}`)
}
const registry: Registry = {
  format: 'pretext-rules/1',
  note: `Generated by rebuild/tests/import-rules.ts from the catalogue of ${catalogue.generatedAt} and rule-changes.json. ${changes.note}`,
  rules: [...byId.values()],
}
writeFileSync(REGISTRY_PATH, `${JSON.stringify(registry, null, 1)}\n`)
const current = registry.rules.filter(rule => rule.status === 'current').length
console.log(`${REGISTRY_PATH}: ${registry.rules.length} rules, ${current} current, ${registry.rules.length - current} removed`)
