#!/usr/bin/env python3
"""Generate a C++ harness that runs WebKit's own BreakablePositions::classify() and lineBreakTable, copied verbatim.

Usage: gen_break_tables.py <BreakablePositions.h> <BreakablePositions.cpp> <harness.cpp> <table.inc> <revision label>

The harness is compiled against system libicucore and writes, into the directory given on its command line:
  classify.tsv                 code-unit ranges U+0000..U+FFFF with the class bits classify() returns, per NBSP behaviour
  linebreak-table-pairs.tsv    for every 'before' in U+0021..U+00FF, the 'after' characters where lineBreakTable breaks
  keepall-punctuation-bmp.tsv  BMP code units whose general category is Ps/Pe/Pi/Pf/Po according to libicucore
                               (the set nextBreakableSpace<..., PunctuationBreaks::Yes> breaks after, if present)
Only text edits: the table declaration line and the two constexpr names in it. Everything else is copied.
"""
import re
import sys

header_path, cpp_path, harness_path, inc_path, label = sys.argv[1:6]
header = open(header_path, encoding='utf-8').read().split('\n')
cpp = open(cpp_path, encoding='utf-8').read().split('\n')

# enum BreakClass
enum_start = next(i for i, l in enumerate(header) if l.strip().startswith('enum BreakClass : uint16_t {'))
enum_end = next(i for i in range(enum_start, len(header)) if header[i].strip() == '};')
enum_text = '\n'.join(header[enum_start:enum_end + 1])

# classify definition
classify_sig = next(i for i, l in enumerate(header) if 'BreakablePositions::classify(char16_t character)' in l)
classify_start = classify_sig - 1
assert header[classify_start].startswith('template<'), header[classify_start]
namespace_end = next(i for i in range(classify_sig, len(header)) if header[i].startswith('} // namespace WebCore'))
classify_end = max(i for i in range(classify_sig, namespace_end) if header[i] == '}')
classify_text = '\n'.join(header[classify_start:classify_end + 1])

# table
define_start = next(i for i, l in enumerate(cpp) if l.startswith('#define B('))
decl = next(i for i, l in enumerate(cpp) if 'BreakablePositions::LineBreakTable::breakTable {' in l)
table_end = next(i for i in range(decl, len(cpp)) if cpp[i].startswith('};'))
table_lines = cpp[define_start:table_end + 1]
table_lines[decl - define_start] = 'static const std::array<std::array<uint8_t, 28>, 223> webkitBreakTable {'
table_text = '\n'.join(table_lines)
table_text = table_text.replace('BreakablePositions::LineBreakTable::columnCount', '28').replace('BreakablePositions::LineBreakTable::rowCount', '223')
rows = re.findall(r'^/\* ([0-9A-F]{2}) ', table_text, re.M)
assert len(rows) == 223, len(rows)
with open(inc_path, 'w', encoding='utf-8') as f:
    f.write('// Copied verbatim from %s\n// %s:%d-%d; only the declaration line is renamed. Regenerate with tools/gen_break_tables.py.\n' % (label, cpp_path.split('/Source/', 1)[-1] if '/Source/' in cpp_path else cpp_path, define_start + 1, table_end + 1))
    f.write(table_text + '\n')

harness = r'''// Generated by gen_break_tables.py from %(label)s. Do not edit.
#include <array>
#include <cstdint>
#include <cstdio>
#include <string>
#include <unicode/uchar.h>

struct BreakablePositions {
    enum class NoBreakSpaceBehavior { Normal, Break };
    enum class LineBreakRules { Normal, Special };
%(enum)s
    template<LineBreakRules, NoBreakSpaceBehavior>
    static inline BreakClass classify(char16_t character);
};

%(classify)s

#include "%(inc)s"

static std::string names(unsigned bits)
{
    if (!bits)
        return "Indeterminate";
    static const std::pair<unsigned, const char*> table[] = {
        { 1u << 0, "AL" }, { 1u << 1, "ID" }, { 1u << 2, "CM" }, { 1u << 3, "OP" }, { 1u << 4, "CP" }, { 1u << 5, "CL" },
        { 1u << 6, "GL" }, { 1u << 7, "QU" }, { 1u << 8, "SP" }, { 1u << 9, "Pi" }, { 1u << 10, "Pf" }, { 1u << 15, "Weird" },
    };
    std::string out;
    for (auto& [bit, name] : table) {
        if (bits & bit) {
            if (!out.empty())
                out += "|";
            out += name;
            bits &= ~bit;
        }
    }
    if (bits)
        out += "|unknown";
    return out;
}

int main(int argc, char** argv)
{
    if (argc < 2)
        return 2;
    std::string dir = argv[1];
    FILE* classify = fopen((dir + "/classify.tsv").c_str(), "w");
    FILE* pairs = fopen((dir + "/linebreak-table-pairs.tsv").c_str(), "w");
    FILE* punctuation = fopen((dir + "/keepall-punctuation-bmp.tsv").c_str(), "w");
    if (!classify || !pairs || !punctuation) {
        perror("open");
        return 1;
    }
    fprintf(classify, "# BreakablePositions::classify() from %(label)s, run over every UTF-16 code unit.\n");
    fprintf(classify, "# rules\tnbsp\tfirst\tlast\tbits\tclasses\n");
    for (int rules = 0; rules < 2; ++rules) {
        for (int nbsp = 0; nbsp < 2; ++nbsp) {
            auto r = rules ? BreakablePositions::LineBreakRules::Special : BreakablePositions::LineBreakRules::Normal;
            auto n = nbsp ? BreakablePositions::NoBreakSpaceBehavior::Break : BreakablePositions::NoBreakSpaceBehavior::Normal;
            unsigned start = 0;
            unsigned current = 0;
            auto emit = [&](unsigned first, unsigned last, unsigned bits) {
                fprintf(classify, "%%s\t%%s\t%%04X\t%%04X\t%%u\t%%s\n", rules ? "Special" : "Normal", nbsp ? "Break" : "Normal", first, last, bits, names(bits).c_str());
            };
            for (unsigned c = 0; c <= 0xFFFF; ++c) {
                unsigned bits = 0;
                switch (r) {
                case BreakablePositions::LineBreakRules::Normal:
                    bits = n == BreakablePositions::NoBreakSpaceBehavior::Normal ? BreakablePositions::classify<BreakablePositions::LineBreakRules::Normal, BreakablePositions::NoBreakSpaceBehavior::Normal>(char16_t(c)) : BreakablePositions::classify<BreakablePositions::LineBreakRules::Normal, BreakablePositions::NoBreakSpaceBehavior::Break>(char16_t(c));
                    break;
                case BreakablePositions::LineBreakRules::Special:
                    bits = n == BreakablePositions::NoBreakSpaceBehavior::Normal ? BreakablePositions::classify<BreakablePositions::LineBreakRules::Special, BreakablePositions::NoBreakSpaceBehavior::Normal>(char16_t(c)) : BreakablePositions::classify<BreakablePositions::LineBreakRules::Special, BreakablePositions::NoBreakSpaceBehavior::Break>(char16_t(c));
                    break;
                }
                if (!c) {
                    current = bits;
                    continue;
                }
                if (bits != current) {
                    emit(start, c - 1, current);
                    start = c;
                    current = bits;
                }
            }
            emit(start, 0xFFFF, current);
        }
    }

    fprintf(pairs, "# lineBreakTable from %(label)s: unsafeLookup(before, after) for before, after in U+0021..U+00FF.\n");
    fprintf(pairs, "# Consulted only with LineBreakRules::Normal, when both characters are <= U+00FF (BreakablePositions.h:181-187).\n");
    fprintf(pairs, "# before\tcount\tafters where a break is allowed before 'after'\n");
    unsigned total = 0;
    for (unsigned before = 0x21; before <= 0xFF; ++before) {
        std::string list;
        unsigned count = 0;
        for (unsigned after = 0x21; after <= 0xFF; ++after) {
            unsigned beforeIndex = before - 0x21;
            unsigned afterIndex = after - 0x21;
            if (webkitBreakTable[beforeIndex][afterIndex / 8] & (1 << (afterIndex %% 8))) {
                char buffer[8];
                snprintf(buffer, sizeof buffer, "%%s%%02X", list.empty() ? "" : " ", after);
                list += buffer;
                ++count;
            }
        }
        total += count;
        fprintf(pairs, "%%02X\t%%u\t%%s\n", before, count, list.c_str());
    }
    fprintf(pairs, "# total breakable pairs: %%u\n", total);

    UVersionInfo version;
    char versionString[U_MAX_VERSION_STRING_LENGTH];
    u_getVersion(version);
    u_versionToString(version, versionString);
    fprintf(punctuation, "# BMP code units c with U_GET_GC_MASK(c) & (Ps|Pe|Pi|Pf|Po), from libicucore u_getVersion=%%s.\n", versionString);
    fprintf(punctuation, "# Used by keep-all on 16-bit text only (BreakablePositions.h:268-271 at 7625; absent at 7624). Surrogates are Cs, so supplementary punctuation never matches.\n");
    fprintf(punctuation, "# first\tlast\n");
    int runStart = -1;
    unsigned punctuationCount = 0;
    for (unsigned c = 0; c <= 0x10000; ++c) {
        bool match = c <= 0xFFFF && (U_GET_GC_MASK(c) & (U_GC_PS_MASK | U_GC_PE_MASK | U_GC_PI_MASK | U_GC_PF_MASK | U_GC_PO_MASK));
        if (match) {
            ++punctuationCount;
            if (runStart < 0)
                runStart = int(c);
        } else if (runStart >= 0) {
            fprintf(punctuation, "%%04X\t%%04X\n", unsigned(runStart), c - 1);
            runStart = -1;
        }
    }
    fprintf(punctuation, "# total code units: %%u\n", punctuationCount);
    fclose(classify);
    fclose(pairs);
    fclose(punctuation);
    fprintf(stderr, "wrote %%s: pairs %%u, punctuation %%u\n", dir.c_str(), total, punctuationCount);
    return 0;
}
''' % {'label': label, 'enum': '\n'.join('    ' + l.strip() if l.strip() else '' for l in enum_text.split('\n')), 'classify': classify_text, 'inc': inc_path.split('/')[-1]}

with open(harness_path, 'w', encoding='utf-8') as f:
    f.write(harness)
print('harness', harness_path, 'table rows', len(rows), 'source lines', define_start + 1, table_end + 1)
